version: '3.8'

services:

  db:
    env_file:
      - .env
    image: mysql
    container_name: mysql_fitee
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mariadb
    networks:
      - friend-gym

  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - friend-gym

  back-end:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: friend-gym
    restart: always
    depends_on:
      - redis
      - db
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      MARIADB_USER: ${MYSQL_USER}
      MARIADB_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8080:8080"
      - "443:443"
    volumes:
      - .:/app
    networks:
      - friend-gym
networks:
  friend-gym:
    driver: bridge

volumes:
  mariadb_data:
