spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop

  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5

    redis:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:h2:mem:mr6208;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  security:
    oauth2:
      client:
        registration:
          google:
            client-secret: ${CLIENT_SECRET}
            client-id: ${CLIENT_ID}
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
              - email
              - profile

jwt:
  secret: asdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdf12
  access-token-expiration-minutes: 600000
  refresh-token-expiration-minutes: 6000000

