name: CD - Deploy to NCP

on:
  push:
    branches:
      - devlop  

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read  
      id-token: write 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Docker Image
        run: |
          docker build -t rm6208/fitee:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: |
          docker push rm6208/fitee:latest

      - name: Deploy to NCP Server via SSH
        env:
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}  
          SERVER_IP: ${{ secrets.SERVER_IP }}  
          SERVER_USER: ${{ secrets.SERVER_USER }}  
        run: |
          sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP << 'EOF'
            
            echo "Stopping running containers..."
            docker-compose down

            echo "Pulling latest Docker image..."
            docker pull rm6208/fitee:latest

            echo "Starting new containers with docker-compose..."
            docker-compose up -d
            
          EOF
